/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  sym_escaped = 5,
  aux_sym__newline_token1 = 6,
  aux_sym__newline_token2 = 7,
  aux_sym__newline_token3 = 8,
  aux_sym_dash_token1 = 9,
  aux_sym_dash_token2 = 10,
  aux_sym_dash_token3 = 11,
  sym__anything_else = 12,
  sym_raw_scope_open = 13,
  sym_raw_scope_contents = 14,
  sym_raw_scope_close = 15,
  sym_eval_bracket_open = 16,
  sym_eval_bracket_contents = 17,
  sym_eval_bracket_close = 18,
  sym_source_file = 19,
  sym__group = 20,
  sym_eval_bracket = 21,
  sym_raw_scope = 22,
  sym_scope = 23,
  sym_comment = 24,
  sym__newline = 25,
  sym_dash = 26,
  aux_sym_source_file_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_escaped] = "escaped",
  [aux_sym__newline_token1] = "_newline_token1",
  [aux_sym__newline_token2] = "_newline_token2",
  [aux_sym__newline_token3] = "_newline_token3",
  [aux_sym_dash_token1] = "dash_token1",
  [aux_sym_dash_token2] = "dash_token2",
  [aux_sym_dash_token3] = "dash_token3",
  [sym__anything_else] = "_anything_else",
  [sym_raw_scope_open] = "raw_scope_open",
  [sym_raw_scope_contents] = "raw_scope_contents",
  [sym_raw_scope_close] = "raw_scope_close",
  [sym_eval_bracket_open] = "eval_bracket_open",
  [sym_eval_bracket_contents] = "eval_bracket_contents",
  [sym_eval_bracket_close] = "eval_bracket_close",
  [sym_source_file] = "source_file",
  [sym__group] = "_group",
  [sym_eval_bracket] = "eval_bracket",
  [sym_raw_scope] = "raw_scope",
  [sym_scope] = "scope",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym_dash] = "dash",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_escaped] = sym_escaped,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [aux_sym__newline_token2] = aux_sym__newline_token2,
  [aux_sym__newline_token3] = aux_sym__newline_token3,
  [aux_sym_dash_token1] = aux_sym_dash_token1,
  [aux_sym_dash_token2] = aux_sym_dash_token2,
  [aux_sym_dash_token3] = aux_sym_dash_token3,
  [sym__anything_else] = sym__anything_else,
  [sym_raw_scope_open] = sym_raw_scope_open,
  [sym_raw_scope_contents] = sym_raw_scope_contents,
  [sym_raw_scope_close] = sym_raw_scope_close,
  [sym_eval_bracket_open] = sym_eval_bracket_open,
  [sym_eval_bracket_contents] = sym_eval_bracket_contents,
  [sym_eval_bracket_close] = sym_eval_bracket_close,
  [sym_source_file] = sym_source_file,
  [sym__group] = sym__group,
  [sym_eval_bracket] = sym_eval_bracket,
  [sym_raw_scope] = sym_raw_scope,
  [sym_scope] = sym_scope,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym_dash] = sym_dash,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token3] = {
    .visible = false,
    .named = false,
  },
  [sym__anything_else] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_scope_open] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_close] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_open] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_close] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym_eval_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_dash] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 11,
  [23] = 9,
  [24] = 8,
  [25] = 7,
  [26] = 10,
  [27] = 19,
  [28] = 6,
  [29] = 21,
  [30] = 18,
  [31] = 16,
  [32] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_escaped);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__newline_token2);
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__newline_token3);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_dash_token1);
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_dash_token2);
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_dash_token3);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__anything_else);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '-' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0, .external_lex_state = 4},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0, .external_lex_state = 5},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_escaped] = ACTIONS(1),
    [aux_sym__newline_token1] = ACTIONS(1),
    [aux_sym__newline_token2] = ACTIONS(1),
    [aux_sym__newline_token3] = ACTIONS(1),
    [aux_sym_dash_token1] = ACTIONS(1),
    [aux_sym_dash_token2] = ACTIONS(1),
    [aux_sym_dash_token3] = ACTIONS(1),
    [sym__anything_else] = ACTIONS(1),
    [sym_raw_scope_open] = ACTIONS(1),
    [sym_raw_scope_contents] = ACTIONS(1),
    [sym_raw_scope_close] = ACTIONS(1),
    [sym_eval_bracket_open] = ACTIONS(1),
    [sym_eval_bracket_contents] = ACTIONS(1),
    [sym_eval_bracket_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym__group] = STATE(2),
    [sym_eval_bracket] = STATE(2),
    [sym_raw_scope] = STATE(2),
    [sym_scope] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__newline] = STATE(2),
    [sym_dash] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(9),
    [aux_sym__newline_token1] = ACTIONS(9),
    [aux_sym__newline_token2] = ACTIONS(11),
    [aux_sym__newline_token3] = ACTIONS(9),
    [aux_sym_dash_token1] = ACTIONS(13),
    [aux_sym_dash_token2] = ACTIONS(13),
    [aux_sym_dash_token3] = ACTIONS(15),
    [sym__anything_else] = ACTIONS(9),
    [sym_raw_scope_open] = ACTIONS(17),
    [sym_eval_bracket_open] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__group] = STATE(3),
    [sym_eval_bracket] = STATE(3),
    [sym_raw_scope] = STATE(3),
    [sym_scope] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__newline] = STATE(3),
    [sym_dash] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(23),
    [aux_sym__newline_token1] = ACTIONS(23),
    [aux_sym__newline_token2] = ACTIONS(25),
    [aux_sym__newline_token3] = ACTIONS(23),
    [aux_sym_dash_token1] = ACTIONS(13),
    [aux_sym_dash_token2] = ACTIONS(13),
    [aux_sym_dash_token3] = ACTIONS(15),
    [sym__anything_else] = ACTIONS(23),
    [sym_raw_scope_open] = ACTIONS(17),
    [sym_eval_bracket_open] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__group] = STATE(3),
    [sym_eval_bracket] = STATE(3),
    [sym_raw_scope] = STATE(3),
    [sym_scope] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__newline] = STATE(3),
    [sym_dash] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_POUND] = ACTIONS(32),
    [sym_escaped] = ACTIONS(35),
    [aux_sym__newline_token1] = ACTIONS(35),
    [aux_sym__newline_token2] = ACTIONS(38),
    [aux_sym__newline_token3] = ACTIONS(35),
    [aux_sym_dash_token1] = ACTIONS(41),
    [aux_sym_dash_token2] = ACTIONS(41),
    [aux_sym_dash_token3] = ACTIONS(44),
    [sym__anything_else] = ACTIONS(35),
    [sym_raw_scope_open] = ACTIONS(47),
    [sym_eval_bracket_open] = ACTIONS(50),
  },
  [STATE(4)] = {
    [sym__group] = STATE(21),
    [sym_eval_bracket] = STATE(21),
    [sym_raw_scope] = STATE(21),
    [sym_scope] = STATE(21),
    [sym_comment] = STATE(21),
    [sym__newline] = STATE(21),
    [sym_dash] = STATE(21),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_POUND] = ACTIONS(55),
    [sym_escaped] = ACTIONS(57),
    [aux_sym__newline_token1] = ACTIONS(57),
    [aux_sym__newline_token2] = ACTIONS(59),
    [aux_sym__newline_token3] = ACTIONS(57),
    [aux_sym_dash_token1] = ACTIONS(61),
    [aux_sym_dash_token2] = ACTIONS(61),
    [aux_sym_dash_token3] = ACTIONS(63),
    [sym__anything_else] = ACTIONS(57),
    [sym_raw_scope_open] = ACTIONS(65),
    [sym_eval_bracket_open] = ACTIONS(67),
  },
  [STATE(5)] = {
    [sym__group] = STATE(29),
    [sym_eval_bracket] = STATE(29),
    [sym_raw_scope] = STATE(29),
    [sym_scope] = STATE(29),
    [sym_comment] = STATE(29),
    [sym__newline] = STATE(29),
    [sym_dash] = STATE(29),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_POUND] = ACTIONS(55),
    [sym_escaped] = ACTIONS(69),
    [aux_sym__newline_token1] = ACTIONS(69),
    [aux_sym__newline_token2] = ACTIONS(71),
    [aux_sym__newline_token3] = ACTIONS(69),
    [aux_sym_dash_token1] = ACTIONS(61),
    [aux_sym_dash_token2] = ACTIONS(61),
    [aux_sym_dash_token3] = ACTIONS(63),
    [sym__anything_else] = ACTIONS(69),
    [sym_raw_scope_open] = ACTIONS(65),
    [sym_eval_bracket_open] = ACTIONS(67),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(75), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(73), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [18] = 2,
    ACTIONS(79), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(77), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [36] = 2,
    ACTIONS(83), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(81), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [54] = 2,
    ACTIONS(87), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(85), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [72] = 2,
    ACTIONS(91), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(89), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [90] = 2,
    ACTIONS(95), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(93), 10,
      sym_raw_scope_open,
      sym_eval_bracket_open,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [108] = 4,
    ACTIONS(97), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 1,
      aux_sym__newline_token2,
    STATE(10), 1,
      sym__newline,
    ACTIONS(99), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [122] = 4,
    ACTIONS(103), 1,
      aux_sym_comment_token1,
    ACTIONS(107), 1,
      aux_sym__newline_token2,
    STATE(26), 1,
      sym__newline,
    ACTIONS(105), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [136] = 3,
    ACTIONS(111), 1,
      aux_sym__newline_token2,
    STATE(7), 1,
      sym__newline,
    ACTIONS(109), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [147] = 3,
    ACTIONS(115), 1,
      aux_sym__newline_token2,
    STATE(25), 1,
      sym__newline,
    ACTIONS(113), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [158] = 1,
    ACTIONS(117), 1,
      sym_eval_bracket_close,
  [162] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [166] = 1,
    ACTIONS(121), 1,
      sym_raw_scope_contents,
  [170] = 1,
    ACTIONS(123), 1,
      sym_raw_scope_close,
  [174] = 1,
    ACTIONS(125), 1,
      sym_eval_bracket_contents,
  [178] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
  [182] = 1,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
  [186] = 1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
  [190] = 1,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
  [194] = 1,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
  [198] = 1,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
  [202] = 1,
    ACTIONS(129), 1,
      sym_raw_scope_close,
  [206] = 1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
  [210] = 1,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
  [214] = 1,
    ACTIONS(133), 1,
      sym_raw_scope_contents,
  [218] = 1,
    ACTIONS(135), 1,
      sym_eval_bracket_close,
  [222] = 1,
    ACTIONS(137), 1,
      sym_eval_bracket_contents,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 18,
  [SMALL_STATE(8)] = 36,
  [SMALL_STATE(9)] = 54,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 90,
  [SMALL_STATE(12)] = 108,
  [SMALL_STATE(13)] = 122,
  [SMALL_STATE(14)] = 136,
  [SMALL_STATE(15)] = 147,
  [SMALL_STATE(16)] = 158,
  [SMALL_STATE(17)] = 162,
  [SMALL_STATE(18)] = 166,
  [SMALL_STATE(19)] = 170,
  [SMALL_STATE(20)] = 174,
  [SMALL_STATE(21)] = 178,
  [SMALL_STATE(22)] = 182,
  [SMALL_STATE(23)] = 186,
  [SMALL_STATE(24)] = 190,
  [SMALL_STATE(25)] = 194,
  [SMALL_STATE(26)] = 198,
  [SMALL_STATE(27)] = 202,
  [SMALL_STATE(28)] = 206,
  [SMALL_STATE(29)] = 210,
  [SMALL_STATE(30)] = 214,
  [SMALL_STATE(31)] = 218,
  [SMALL_STATE(32)] = 222,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_bracket, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eval_bracket, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_scope, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_scope, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dash, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dash, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [119] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_scope_open = 0,
  ts_external_token_raw_scope_contents = 1,
  ts_external_token_raw_scope_close = 2,
  ts_external_token_eval_bracket_open = 3,
  ts_external_token_eval_bracket_contents = 4,
  ts_external_token_eval_bracket_close = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_scope_open] = sym_raw_scope_open,
  [ts_external_token_raw_scope_contents] = sym_raw_scope_contents,
  [ts_external_token_raw_scope_close] = sym_raw_scope_close,
  [ts_external_token_eval_bracket_open] = sym_eval_bracket_open,
  [ts_external_token_eval_bracket_contents] = sym_eval_bracket_contents,
  [ts_external_token_eval_bracket_close] = sym_eval_bracket_close,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_scope_open] = true,
    [ts_external_token_raw_scope_contents] = true,
    [ts_external_token_raw_scope_close] = true,
    [ts_external_token_eval_bracket_open] = true,
    [ts_external_token_eval_bracket_contents] = true,
    [ts_external_token_eval_bracket_close] = true,
  },
  [2] = {
    [ts_external_token_raw_scope_open] = true,
    [ts_external_token_eval_bracket_open] = true,
  },
  [3] = {
    [ts_external_token_eval_bracket_close] = true,
  },
  [4] = {
    [ts_external_token_raw_scope_contents] = true,
  },
  [5] = {
    [ts_external_token_raw_scope_close] = true,
  },
  [6] = {
    [ts_external_token_eval_bracket_contents] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_turnip_text_external_scanner_create(void);
void tree_sitter_turnip_text_external_scanner_destroy(void *);
bool tree_sitter_turnip_text_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_turnip_text_external_scanner_serialize(void *, char *);
void tree_sitter_turnip_text_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_turnip_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_turnip_text_external_scanner_create,
      tree_sitter_turnip_text_external_scanner_destroy,
      tree_sitter_turnip_text_external_scanner_scan,
      tree_sitter_turnip_text_external_scanner_serialize,
      tree_sitter_turnip_text_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "turnip_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
