/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  sym_escaped = 5,
  aux_sym__newline_token1 = 6,
  aux_sym__newline_token2 = 7,
  aux_sym__newline_token3 = 8,
  aux_sym_dash_token1 = 9,
  aux_sym_dash_token2 = 10,
  aux_sym_dash_token3 = 11,
  sym__anything_else = 12,
  sym_raw_scope_open = 13,
  sym_raw_scope_contents = 14,
  sym_raw_scope_close = 15,
  sym_eval_bracket_open = 16,
  sym_eval_bracket_contents = 17,
  sym_eval_bracket_close = 18,
  sym_source_file = 19,
  sym__group = 20,
  sym_scope = 21,
  sym_comment = 22,
  sym__newline = 23,
  sym_dash = 24,
  aux_sym_source_file_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_escaped] = "escaped",
  [aux_sym__newline_token1] = "_newline_token1",
  [aux_sym__newline_token2] = "_newline_token2",
  [aux_sym__newline_token3] = "_newline_token3",
  [aux_sym_dash_token1] = "dash_token1",
  [aux_sym_dash_token2] = "dash_token2",
  [aux_sym_dash_token3] = "dash_token3",
  [sym__anything_else] = "_anything_else",
  [sym_raw_scope_open] = "raw_scope_open",
  [sym_raw_scope_contents] = "raw_scope_contents",
  [sym_raw_scope_close] = "raw_scope_close",
  [sym_eval_bracket_open] = "eval_bracket_open",
  [sym_eval_bracket_contents] = "eval_bracket_contents",
  [sym_eval_bracket_close] = "eval_bracket_close",
  [sym_source_file] = "source_file",
  [sym__group] = "_group",
  [sym_scope] = "scope",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym_dash] = "dash",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_escaped] = sym_escaped,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [aux_sym__newline_token2] = aux_sym__newline_token2,
  [aux_sym__newline_token3] = aux_sym__newline_token3,
  [aux_sym_dash_token1] = aux_sym_dash_token1,
  [aux_sym_dash_token2] = aux_sym_dash_token2,
  [aux_sym_dash_token3] = aux_sym_dash_token3,
  [sym__anything_else] = sym__anything_else,
  [sym_raw_scope_open] = sym_raw_scope_open,
  [sym_raw_scope_contents] = sym_raw_scope_contents,
  [sym_raw_scope_close] = sym_raw_scope_close,
  [sym_eval_bracket_open] = sym_eval_bracket_open,
  [sym_eval_bracket_contents] = sym_eval_bracket_contents,
  [sym_eval_bracket_close] = sym_eval_bracket_close,
  [sym_source_file] = sym_source_file,
  [sym__group] = sym__group,
  [sym_scope] = sym_scope,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym_dash] = sym_dash,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dash_token3] = {
    .visible = false,
    .named = false,
  },
  [sym__anything_else] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_scope_open] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_close] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_open] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_close] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_dash] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_escaped);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__newline_token2);
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__newline_token3);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_dash_token1);
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_dash_token2);
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_dash_token3);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__anything_else);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '-' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_escaped] = ACTIONS(1),
    [aux_sym__newline_token1] = ACTIONS(1),
    [aux_sym__newline_token2] = ACTIONS(1),
    [aux_sym__newline_token3] = ACTIONS(1),
    [aux_sym_dash_token1] = ACTIONS(1),
    [aux_sym_dash_token2] = ACTIONS(1),
    [aux_sym_dash_token3] = ACTIONS(1),
    [sym__anything_else] = ACTIONS(1),
    [sym_raw_scope_open] = ACTIONS(1),
    [sym_raw_scope_contents] = ACTIONS(1),
    [sym_raw_scope_close] = ACTIONS(1),
    [sym_eval_bracket_open] = ACTIONS(1),
    [sym_eval_bracket_contents] = ACTIONS(1),
    [sym_eval_bracket_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(11),
    [sym__group] = STATE(2),
    [sym_scope] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__newline] = STATE(2),
    [sym_dash] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(9),
    [aux_sym__newline_token1] = ACTIONS(9),
    [aux_sym__newline_token2] = ACTIONS(11),
    [aux_sym__newline_token3] = ACTIONS(9),
    [aux_sym_dash_token1] = ACTIONS(13),
    [aux_sym_dash_token2] = ACTIONS(13),
    [aux_sym_dash_token3] = ACTIONS(15),
    [sym__anything_else] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__group] = STATE(3),
    [sym_scope] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__newline] = STATE(3),
    [sym_dash] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(19),
    [aux_sym__newline_token1] = ACTIONS(19),
    [aux_sym__newline_token2] = ACTIONS(21),
    [aux_sym__newline_token3] = ACTIONS(19),
    [aux_sym_dash_token1] = ACTIONS(13),
    [aux_sym_dash_token2] = ACTIONS(13),
    [aux_sym_dash_token3] = ACTIONS(15),
    [sym__anything_else] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__group] = STATE(3),
    [sym_scope] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__newline] = STATE(3),
    [sym_dash] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(28),
    [sym_escaped] = ACTIONS(31),
    [aux_sym__newline_token1] = ACTIONS(31),
    [aux_sym__newline_token2] = ACTIONS(34),
    [aux_sym__newline_token3] = ACTIONS(31),
    [aux_sym_dash_token1] = ACTIONS(37),
    [aux_sym_dash_token2] = ACTIONS(37),
    [aux_sym_dash_token3] = ACTIONS(40),
    [sym__anything_else] = ACTIONS(31),
  },
  [STATE(4)] = {
    [sym__group] = STATE(12),
    [sym_scope] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__newline] = STATE(12),
    [sym_dash] = STATE(12),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(43),
    [aux_sym__newline_token1] = ACTIONS(43),
    [aux_sym__newline_token2] = ACTIONS(45),
    [aux_sym__newline_token3] = ACTIONS(43),
    [aux_sym_dash_token1] = ACTIONS(13),
    [aux_sym_dash_token2] = ACTIONS(13),
    [aux_sym_dash_token3] = ACTIONS(15),
    [sym__anything_else] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(49), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(47), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [17] = 2,
    ACTIONS(53), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [34] = 2,
    ACTIONS(57), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [51] = 2,
    ACTIONS(61), 3,
      aux_sym__newline_token2,
      aux_sym_dash_token1,
      aux_sym_dash_token2,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      sym_escaped,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
      aux_sym_dash_token3,
      sym__anything_else,
  [68] = 4,
    ACTIONS(63), 1,
      aux_sym_comment_token1,
    ACTIONS(67), 1,
      aux_sym__newline_token2,
    STATE(6), 1,
      sym__newline,
    ACTIONS(65), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [82] = 3,
    ACTIONS(71), 1,
      aux_sym__newline_token2,
    STATE(8), 1,
      sym__newline,
    ACTIONS(69), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [93] = 1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
  [97] = 1,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 17,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 68,
  [SMALL_STATE(10)] = 82,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 97,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dash, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dash, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_scope_open = 0,
  ts_external_token_raw_scope_contents = 1,
  ts_external_token_raw_scope_close = 2,
  ts_external_token_eval_bracket_open = 3,
  ts_external_token_eval_bracket_contents = 4,
  ts_external_token_eval_bracket_close = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_scope_open] = sym_raw_scope_open,
  [ts_external_token_raw_scope_contents] = sym_raw_scope_contents,
  [ts_external_token_raw_scope_close] = sym_raw_scope_close,
  [ts_external_token_eval_bracket_open] = sym_eval_bracket_open,
  [ts_external_token_eval_bracket_contents] = sym_eval_bracket_contents,
  [ts_external_token_eval_bracket_close] = sym_eval_bracket_close,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_scope_open] = true,
    [ts_external_token_raw_scope_contents] = true,
    [ts_external_token_raw_scope_close] = true,
    [ts_external_token_eval_bracket_open] = true,
    [ts_external_token_eval_bracket_contents] = true,
    [ts_external_token_eval_bracket_close] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_turnip_text_external_scanner_create(void);
void tree_sitter_turnip_text_external_scanner_destroy(void *);
bool tree_sitter_turnip_text_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_turnip_text_external_scanner_serialize(void *, char *);
void tree_sitter_turnip_text_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_turnip_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_turnip_text_external_scanner_create,
      tree_sitter_turnip_text_external_scanner_destroy,
      tree_sitter_turnip_text_external_scanner_scan,
      tree_sitter_turnip_text_external_scanner_serialize,
      tree_sitter_turnip_text_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "turnip_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
