/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_scope_open = 1,
  sym_scope_close = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  sym_escaped = 5,
  aux_sym__newline_token1 = 6,
  aux_sym__newline_token2 = 7,
  aux_sym__newline_token3 = 8,
  sym_dash = 9,
  sym_endash = 10,
  sym_emdash = 11,
  sym__whitespace = 12,
  sym__anything_else = 13,
  sym_raw_scope_open = 14,
  sym_raw_scope_contents = 15,
  sym_raw_scope_close = 16,
  sym_eval_bracket_open = 17,
  sym_eval_bracket_contents = 18,
  sym_eval_bracket_close = 19,
  sym_eval_bracket_identifier = 20,
  sym_source_file = 21,
  sym__group = 22,
  sym_eval_bracket = 23,
  sym_raw_scope = 24,
  sym_scope = 25,
  sym_comment = 26,
  sym__newline = 27,
  aux_sym_source_file_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_scope_open] = "scope_open",
  [sym_scope_close] = "scope_close",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_escaped] = "escaped",
  [aux_sym__newline_token1] = "_newline_token1",
  [aux_sym__newline_token2] = "_newline_token2",
  [aux_sym__newline_token3] = "_newline_token3",
  [sym_dash] = "dash",
  [sym_endash] = "endash",
  [sym_emdash] = "emdash",
  [sym__whitespace] = "_whitespace",
  [sym__anything_else] = "_anything_else",
  [sym_raw_scope_open] = "raw_scope_open",
  [sym_raw_scope_contents] = "raw_scope_contents",
  [sym_raw_scope_close] = "raw_scope_close",
  [sym_eval_bracket_open] = "eval_bracket_open",
  [sym_eval_bracket_contents] = "eval_bracket_contents",
  [sym_eval_bracket_close] = "eval_bracket_close",
  [sym_eval_bracket_identifier] = "eval_bracket_identifier",
  [sym_source_file] = "source_file",
  [sym__group] = "_group",
  [sym_eval_bracket] = "eval_bracket",
  [sym_raw_scope] = "raw_scope",
  [sym_scope] = "scope",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_scope_open] = sym_scope_open,
  [sym_scope_close] = sym_scope_close,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_escaped] = sym_escaped,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [aux_sym__newline_token2] = aux_sym__newline_token2,
  [aux_sym__newline_token3] = aux_sym__newline_token3,
  [sym_dash] = sym_dash,
  [sym_endash] = sym_endash,
  [sym_emdash] = sym_emdash,
  [sym__whitespace] = sym__whitespace,
  [sym__anything_else] = sym__anything_else,
  [sym_raw_scope_open] = sym_raw_scope_open,
  [sym_raw_scope_contents] = sym_raw_scope_contents,
  [sym_raw_scope_close] = sym_raw_scope_close,
  [sym_eval_bracket_open] = sym_eval_bracket_open,
  [sym_eval_bracket_contents] = sym_eval_bracket_contents,
  [sym_eval_bracket_close] = sym_eval_bracket_close,
  [sym_eval_bracket_identifier] = sym_eval_bracket_identifier,
  [sym_source_file] = sym_source_file,
  [sym__group] = sym__group,
  [sym_eval_bracket] = sym_eval_bracket,
  [sym_raw_scope] = sym_raw_scope,
  [sym_scope] = sym_scope,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_scope_open] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__newline_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_dash] = {
    .visible = true,
    .named = true,
  },
  [sym_endash] = {
    .visible = true,
    .named = true,
  },
  [sym_emdash] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym__anything_else] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_scope_open] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope_close] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_open] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_close] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_bracket_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym_eval_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '\n', 14,
        '\r', 11,
        '#', 6,
        '-', 15,
        '\\', 2,
        '{', 4,
        '}', 5,
        '\t', 18,
        0x0b, 18,
        '\f', 18,
        ' ', 18,
      );
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_scope_open);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_scope_close);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_escaped);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__newline_token2);
      if (lookahead == '\n') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__newline_token2);
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__newline_token3);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__newline_token3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_dash);
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_endash);
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_emdash);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__anything_else);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '-' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_scope_open] = ACTIONS(1),
    [sym_scope_close] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_escaped] = ACTIONS(1),
    [aux_sym__newline_token1] = ACTIONS(1),
    [aux_sym__newline_token2] = ACTIONS(1),
    [aux_sym__newline_token3] = ACTIONS(1),
    [sym_dash] = ACTIONS(1),
    [sym_endash] = ACTIONS(1),
    [sym_emdash] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(1),
    [sym__anything_else] = ACTIONS(1),
    [sym_raw_scope_open] = ACTIONS(1),
    [sym_raw_scope_contents] = ACTIONS(1),
    [sym_raw_scope_close] = ACTIONS(1),
    [sym_eval_bracket_open] = ACTIONS(1),
    [sym_eval_bracket_contents] = ACTIONS(1),
    [sym_eval_bracket_close] = ACTIONS(1),
    [sym_eval_bracket_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym__group] = STATE(4),
    [sym_eval_bracket] = STATE(4),
    [sym_raw_scope] = STATE(4),
    [sym_scope] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__newline] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_scope_open] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(9),
    [aux_sym__newline_token1] = ACTIONS(11),
    [aux_sym__newline_token2] = ACTIONS(11),
    [aux_sym__newline_token3] = ACTIONS(11),
    [sym_dash] = ACTIONS(11),
    [sym_endash] = ACTIONS(11),
    [sym_emdash] = ACTIONS(9),
    [sym__whitespace] = ACTIONS(11),
    [sym__anything_else] = ACTIONS(9),
    [sym_raw_scope_open] = ACTIONS(13),
    [sym_eval_bracket_open] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__group] = STATE(2),
    [sym_eval_bracket] = STATE(2),
    [sym_raw_scope] = STATE(2),
    [sym_scope] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__newline] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_scope_open] = ACTIONS(19),
    [sym_scope_close] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(22),
    [sym_escaped] = ACTIONS(25),
    [aux_sym__newline_token1] = ACTIONS(28),
    [aux_sym__newline_token2] = ACTIONS(28),
    [aux_sym__newline_token3] = ACTIONS(28),
    [sym_dash] = ACTIONS(28),
    [sym_endash] = ACTIONS(28),
    [sym_emdash] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(28),
    [sym__anything_else] = ACTIONS(25),
    [sym_raw_scope_open] = ACTIONS(31),
    [sym_eval_bracket_open] = ACTIONS(34),
  },
  [STATE(3)] = {
    [sym__group] = STATE(5),
    [sym_eval_bracket] = STATE(5),
    [sym_raw_scope] = STATE(5),
    [sym_scope] = STATE(5),
    [sym_comment] = STATE(5),
    [sym__newline] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_scope_open] = ACTIONS(5),
    [sym_scope_close] = ACTIONS(37),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(39),
    [aux_sym__newline_token1] = ACTIONS(41),
    [aux_sym__newline_token2] = ACTIONS(41),
    [aux_sym__newline_token3] = ACTIONS(41),
    [sym_dash] = ACTIONS(41),
    [sym_endash] = ACTIONS(41),
    [sym_emdash] = ACTIONS(39),
    [sym__whitespace] = ACTIONS(41),
    [sym__anything_else] = ACTIONS(39),
    [sym_raw_scope_open] = ACTIONS(13),
    [sym_eval_bracket_open] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym__group] = STATE(2),
    [sym_eval_bracket] = STATE(2),
    [sym_raw_scope] = STATE(2),
    [sym_scope] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__newline] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_scope_open] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(45),
    [aux_sym__newline_token1] = ACTIONS(47),
    [aux_sym__newline_token2] = ACTIONS(47),
    [aux_sym__newline_token3] = ACTIONS(47),
    [sym_dash] = ACTIONS(47),
    [sym_endash] = ACTIONS(47),
    [sym_emdash] = ACTIONS(45),
    [sym__whitespace] = ACTIONS(47),
    [sym__anything_else] = ACTIONS(45),
    [sym_raw_scope_open] = ACTIONS(13),
    [sym_eval_bracket_open] = ACTIONS(15),
  },
  [STATE(5)] = {
    [sym__group] = STATE(2),
    [sym_eval_bracket] = STATE(2),
    [sym_raw_scope] = STATE(2),
    [sym_scope] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__newline] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_scope_open] = ACTIONS(5),
    [sym_scope_close] = ACTIONS(49),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_escaped] = ACTIONS(45),
    [aux_sym__newline_token1] = ACTIONS(47),
    [aux_sym__newline_token2] = ACTIONS(47),
    [aux_sym__newline_token3] = ACTIONS(47),
    [sym_dash] = ACTIONS(47),
    [sym_endash] = ACTIONS(47),
    [sym_emdash] = ACTIONS(45),
    [sym__whitespace] = ACTIONS(47),
    [sym__anything_else] = ACTIONS(45),
    [sym_raw_scope_open] = ACTIONS(13),
    [sym_eval_bracket_open] = ACTIONS(15),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_scope_open] = ACTIONS(51),
    [sym_scope_close] = ACTIONS(51),
    [anon_sym_POUND] = ACTIONS(51),
    [sym_escaped] = ACTIONS(51),
    [aux_sym__newline_token1] = ACTIONS(53),
    [aux_sym__newline_token2] = ACTIONS(53),
    [aux_sym__newline_token3] = ACTIONS(53),
    [sym_dash] = ACTIONS(53),
    [sym_endash] = ACTIONS(53),
    [sym_emdash] = ACTIONS(51),
    [sym__whitespace] = ACTIONS(53),
    [sym__anything_else] = ACTIONS(51),
    [sym_raw_scope_open] = ACTIONS(51),
    [sym_eval_bracket_open] = ACTIONS(51),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_scope_open] = ACTIONS(55),
    [sym_scope_close] = ACTIONS(55),
    [anon_sym_POUND] = ACTIONS(55),
    [sym_escaped] = ACTIONS(55),
    [aux_sym__newline_token1] = ACTIONS(57),
    [aux_sym__newline_token2] = ACTIONS(57),
    [aux_sym__newline_token3] = ACTIONS(57),
    [sym_dash] = ACTIONS(57),
    [sym_endash] = ACTIONS(57),
    [sym_emdash] = ACTIONS(55),
    [sym__whitespace] = ACTIONS(57),
    [sym__anything_else] = ACTIONS(55),
    [sym_raw_scope_open] = ACTIONS(55),
    [sym_eval_bracket_open] = ACTIONS(55),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_scope_open] = ACTIONS(59),
    [sym_scope_close] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(59),
    [sym_escaped] = ACTIONS(59),
    [aux_sym__newline_token1] = ACTIONS(61),
    [aux_sym__newline_token2] = ACTIONS(61),
    [aux_sym__newline_token3] = ACTIONS(61),
    [sym_dash] = ACTIONS(61),
    [sym_endash] = ACTIONS(61),
    [sym_emdash] = ACTIONS(59),
    [sym__whitespace] = ACTIONS(61),
    [sym__anything_else] = ACTIONS(59),
    [sym_raw_scope_open] = ACTIONS(59),
    [sym_eval_bracket_open] = ACTIONS(59),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_scope_open] = ACTIONS(63),
    [sym_scope_close] = ACTIONS(63),
    [anon_sym_POUND] = ACTIONS(63),
    [sym_escaped] = ACTIONS(63),
    [aux_sym__newline_token1] = ACTIONS(65),
    [aux_sym__newline_token2] = ACTIONS(65),
    [aux_sym__newline_token3] = ACTIONS(65),
    [sym_dash] = ACTIONS(65),
    [sym_endash] = ACTIONS(65),
    [sym_emdash] = ACTIONS(63),
    [sym__whitespace] = ACTIONS(65),
    [sym__anything_else] = ACTIONS(63),
    [sym_raw_scope_open] = ACTIONS(63),
    [sym_eval_bracket_open] = ACTIONS(63),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_scope_open] = ACTIONS(67),
    [sym_scope_close] = ACTIONS(67),
    [anon_sym_POUND] = ACTIONS(67),
    [sym_escaped] = ACTIONS(67),
    [aux_sym__newline_token1] = ACTIONS(69),
    [aux_sym__newline_token2] = ACTIONS(69),
    [aux_sym__newline_token3] = ACTIONS(69),
    [sym_dash] = ACTIONS(69),
    [sym_endash] = ACTIONS(69),
    [sym_emdash] = ACTIONS(67),
    [sym__whitespace] = ACTIONS(69),
    [sym__anything_else] = ACTIONS(67),
    [sym_raw_scope_open] = ACTIONS(67),
    [sym_eval_bracket_open] = ACTIONS(67),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_scope_open] = ACTIONS(71),
    [sym_scope_close] = ACTIONS(71),
    [anon_sym_POUND] = ACTIONS(71),
    [sym_escaped] = ACTIONS(71),
    [aux_sym__newline_token1] = ACTIONS(73),
    [aux_sym__newline_token2] = ACTIONS(73),
    [aux_sym__newline_token3] = ACTIONS(73),
    [sym_dash] = ACTIONS(73),
    [sym_endash] = ACTIONS(73),
    [sym_emdash] = ACTIONS(71),
    [sym__whitespace] = ACTIONS(73),
    [sym__anything_else] = ACTIONS(71),
    [sym_raw_scope_open] = ACTIONS(71),
    [sym_eval_bracket_open] = ACTIONS(71),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(75), 1,
      aux_sym_comment_token1,
    ACTIONS(79), 1,
      aux_sym__newline_token2,
    STATE(7), 1,
      sym__newline,
    ACTIONS(77), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [14] = 3,
    ACTIONS(83), 1,
      aux_sym__newline_token2,
    STATE(11), 1,
      sym__newline,
    ACTIONS(81), 2,
      aux_sym__newline_token1,
      aux_sym__newline_token3,
  [25] = 1,
    ACTIONS(85), 2,
      sym_eval_bracket_contents,
      sym_eval_bracket_identifier,
  [30] = 1,
    ACTIONS(87), 1,
      sym_raw_scope_contents,
  [34] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [38] = 1,
    ACTIONS(91), 1,
      sym_raw_scope_close,
  [42] = 1,
    ACTIONS(93), 1,
      sym_eval_bracket_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 14,
  [SMALL_STATE(14)] = 25,
  [SMALL_STATE(15)] = 30,
  [SMALL_STATE(16)] = 34,
  [SMALL_STATE(17)] = 38,
  [SMALL_STATE(18)] = 42,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_scope, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_scope, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_bracket, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eval_bracket, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_scope_open = 0,
  ts_external_token_raw_scope_contents = 1,
  ts_external_token_raw_scope_close = 2,
  ts_external_token_eval_bracket_open = 3,
  ts_external_token_eval_bracket_contents = 4,
  ts_external_token_eval_bracket_close = 5,
  ts_external_token_eval_bracket_identifier = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_scope_open] = sym_raw_scope_open,
  [ts_external_token_raw_scope_contents] = sym_raw_scope_contents,
  [ts_external_token_raw_scope_close] = sym_raw_scope_close,
  [ts_external_token_eval_bracket_open] = sym_eval_bracket_open,
  [ts_external_token_eval_bracket_contents] = sym_eval_bracket_contents,
  [ts_external_token_eval_bracket_close] = sym_eval_bracket_close,
  [ts_external_token_eval_bracket_identifier] = sym_eval_bracket_identifier,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_scope_open] = true,
    [ts_external_token_raw_scope_contents] = true,
    [ts_external_token_raw_scope_close] = true,
    [ts_external_token_eval_bracket_open] = true,
    [ts_external_token_eval_bracket_contents] = true,
    [ts_external_token_eval_bracket_close] = true,
    [ts_external_token_eval_bracket_identifier] = true,
  },
  [2] = {
    [ts_external_token_raw_scope_open] = true,
    [ts_external_token_eval_bracket_open] = true,
  },
  [3] = {
    [ts_external_token_eval_bracket_contents] = true,
    [ts_external_token_eval_bracket_identifier] = true,
  },
  [4] = {
    [ts_external_token_raw_scope_contents] = true,
  },
  [5] = {
    [ts_external_token_raw_scope_close] = true,
  },
  [6] = {
    [ts_external_token_eval_bracket_close] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_turnip_text_external_scanner_create(void);
void tree_sitter_turnip_text_external_scanner_destroy(void *);
bool tree_sitter_turnip_text_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_turnip_text_external_scanner_serialize(void *, char *);
void tree_sitter_turnip_text_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_turnip_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_turnip_text_external_scanner_create,
      tree_sitter_turnip_text_external_scanner_destroy,
      tree_sitter_turnip_text_external_scanner_scan,
      tree_sitter_turnip_text_external_scanner_serialize,
      tree_sitter_turnip_text_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "turnip_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
